version: '3.8'
services:
  deeplx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOOS: linux
        GOARCH: amd64
    image: neccen/deeplx-local:latest
    ports:
      - "62155:62155"
    container_name: deeplx
    restart: unless-stopped